# Generated by Django 3.0.7 on 2020-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_auto_20200627_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EURO Order Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EURO Price'),
        ),
    ]
